#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

// Include the helper functions
require __DIR__ . '/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

// Set the application instance globally
Illuminate\Container\Container::setInstance($app);

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

$kernel->terminate($input, $status);

exit($status);
